# Generated by Django 4.1.1 on 2022-09-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=32)),
                ('lastName', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('title', models.CharField(max_length=32)),
                ('pay', models.IntegerField()),
            ],
        ),
    ]
